## Selección de varaibles

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [2]:
lendingclub = pd.read_csv('./data/01_raw_general.csv', sep = ',')
lendingclub.head()

C:\Users\nacho\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3071: DtypeWarning: Columns (19,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,112435993,NaN,2300.0,2300.0,2300.0,36 months,12.62%,77.08,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,112290210,NaN,16000.0,16000.0,16000.0,60 months,12.62%,360.95,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,112436985,NaN,6025.0,6025.0,6025.0,36 months,15.05%,209.01,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,112439006,NaN,20400.0,20400.0,20400.0,36 months,9.44%,652.91,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,112438929,NaN,13000.0,13000.0,13000.0,36 months,11.99%,431.73,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

### Variables con NA

En primer lugar, quitamos todos aquellas variables con un número considerable de valores perdidos que pueden influir negativamente en nuestros modelos. En este caso consideramos quitar todas aquellas variables con más de 431,425 NA. Podemos observar el número de missing values en la siguiente tabla.

In [3]:
na_columnas = pd.DataFrame(lendingclub.isna().sum(), columns = ['Valores NaN']).sort_values(['Valores NaN'], ascending = False)
pd.set_option('display.max_rows', nacolumnas.shape[0]+1)
print(na_columnas)

                                            Valores NaN
member_id                                        884876
orig_projected_additional_accrued_interest       882607
hardship_end_date                                882215
hardship_amount                                  882215
hardship_type                                    882215
hardship_reason                                  882215
hardship_status                                  882215
hardship_last_payment_amount                     882215
hardship_payoff_balance_amount                   882215
hardship_loan_status                             882215
hardship_dpd                                     882215
hardship_length                                  882215
payment_plan_start_date                          882215
deferral_term                                    882215
hardship_start_date                              882215
sec_app_mths_since_last_major_derog              877691
settlement_term                                  876356
debt_settlement_flag_date                        876356
settlement_status                                876356
settlement_date                                  876356
settlement_amount                                876356
settlement_percentage                            876356
desc                                             869552
sec_app_revol_util                               864358
sec_app_inq_last_6mths                           864076
revol_bal_joint                                  864076
sec_app_fico_range_low                           864076
sec_app_fico_range_high                          864076
sec_app_earliest_cr_line                         864076
sec_app_open_act_il                              864076
sec_app_mort_acc                                 864076
sec_app_chargeoff_within_12_mths                 864076
sec_app_open_acc                                 864076
sec_app_collections_12_mths_ex_med               864076
sec_app_num_rev_accts                            864076
dti_joint                                        863560
verification_status_joint                        863558
annual_inc_joint                                 863558
mths_since_last_record                           729776
il_util                                          668295
mths_since_recent_bc_dlq                         659442
mths_since_rcnt_il                               642103
all_util                                         635379
open_rv_24m                                      635352
open_rv_12m                                      635352
inq_last_12m                                     635352
total_bal_il                                     635352
open_il_24m                                      635352
open_il_12m                                      635352
open_act_il                                      635352
open_acc_6m                                      635352
total_cu_tl                                      635352
max_bal_bc                                       635352
inq_fi                                           635352
mths_since_last_major_derog                      633263
mths_since_recent_revol_delinq                   569042
next_pymnt_d                                     442567
mths_since_last_delinq                           431427
mths_since_recent_inq                             92130
emp_title                                         52693
emp_length                                        51193
num_tl_120dpd_2m                                  37803
mo_sin_old_il_acct                                25614
bc_util                                            9824
percent_bc_gt_75                                   9680
bc_open_to_buy                                     9287
mths_since_recent_bc                               8763
last_pymnt_d                                        758
revol_util                                          489
dti                                                 261
title                                               132
last_credit_pull_d                                   38
avg_cur_bal                                          13
num_rev_accts                                         1
annual_inc                                            0
fico_range_low                                        0
fico_range_high                                       0
inq_last_6mths                                        0
funded_amnt                                           0
open_acc                                              0
pub_rec                                               0
revol_bal                                             0
grade                                                 0
term                                                  0
total_il_high_credit_limit                            0
loan_amnt                                             0
total_bc_limit                                        0
total_bal_ex_mort                                     0
tot_hi_cred_lim                                       0
tax_liens                                             0
funded_amnt_inv                                       0
earliest_cr_line                                      0
verification_status                                   0
pub_rec_bankruptcies                                  0
issue_d                                               0
loan_status                                           0
pymnt_plan                                            0
url                                                   0
purpose                                               0
home_ownership                                        0
debt_settlement_flag                                  0
sub_grade                                             0
hardship_flag                                         0
int_rate                                              0
zip_code                                              0
installment                                           0
disbursement_method                                   0
delinq_2yrs                                           0
addr_state                                            0
num_sats                                              0
pct_tl_nvr_dlq                                        0
initial_list_status                                   0
out_prncp_inv                                         0
total_rev_hi_lim                                      0
total_pymnt                                           0
total_pymnt_inv                                       0
total_rec_prncp                                       0
total_rec_int                                         0
total_rec_late_fee                                    0
recoveries                                            0
collection_recovery_fee                               0
last_pymnt_amnt                                       0
tot_cur_bal                                           0
tot_coll_amt                                          0
acc_now_delinq                                        0
last_fico_range_high                                  0
last_fico_range_low                                   0
collections_12_mths_ex_med                            0
application_type                                      0
out_prncp                                             0
acc_open_past_24mths                                  0
num_tl_op_past_12m                                    0
chargeoff_within_12_mths                              0
num_tl_90g_dpd_24m                                    0
num_tl_30dpd                                          0
policy_code                                           0
num_rev_tl_bal_gt_0                                   0
num_op_rev_tl                                         0
num_il_tl                                             0
num_bc_tl                                             0
num_bc_sats                                           0
num_actv_rev_tl                                       0
num_actv_bc_tl                                        0
num_accts_ever_120_pd                                 0
total_acc                                             0
mort_acc                                              0
mo_sin_rcnt_tl                                        0
mo_sin_rcnt_rev_tl_op                                 0
mo_sin_old_rev_tl_op                                  0
delinq_amnt                                           0
id                                                    0

In [4]:
lendingclub1 = lendingclub.dropna(thresh=len(lendingclub) - 431425, axis=1)

In [6]:
na_columnas1  = pd.DataFrame(lendingclub1.isna().sum(), columns = ['Valores NaN']).sort_values(['Valores NaN'], ascending = False)
pd.set_option('display.max_rows', na_columnas1.shape[0]+1)
na_columnas1

                            Valores NaN
mths_since_recent_inq             92130
emp_title                         52693
emp_length                        51193
num_tl_120dpd_2m                  37803
mo_sin_old_il_acct                25614
bc_util                            9824
percent_bc_gt_75                   9680
bc_open_to_buy                     9287
mths_since_recent_bc               8763
last_pymnt_d                        758
revol_util                          489
dti                                 261
title                               132
last_credit_pull_d                   38
avg_cur_bal                          13
num_rev_accts                         1
mo_sin_rcnt_tl                        0
mort_acc                              0
mo_sin_rcnt_rev_tl_op                 0
id                                    0
mo_sin_old_rev_tl_op                  0
delinq_amnt                           0
num_accts_ever_120_pd                 0
acc_open_past_24mths                  0
total_rev_hi_lim                      0
tot_cur_bal                           0
tot_coll_amt                          0
chargeoff_within_12_mths              0
num_bc_tl                             0
num_actv_bc_tl                        0
pct_tl_nvr_dlq                        0
disbursement_method                   0
hardship_flag                         0
total_il_high_credit_limit            0
total_bc_limit                        0
total_bal_ex_mort                     0
tot_hi_cred_lim                       0
tax_liens                             0
pub_rec_bankruptcies                  0
num_tl_op_past_12m                    0
num_actv_rev_tl                       0
num_tl_90g_dpd_24m                    0
num_tl_30dpd                          0
num_sats                              0
num_rev_tl_bal_gt_0                   0
num_op_rev_tl                         0
num_il_tl                             0
application_type                      0
num_bc_sats                           0
acc_now_delinq                        0
last_fico_range_high                  0
policy_code                           0
verification_status                   0
delinq_2yrs                           0
addr_state                            0
zip_code                              0
purpose                               0
url                                   0
pymnt_plan                            0
loan_status                           0
issue_d                               0
annual_inc                            0
collections_12_mths_ex_med            0
home_ownership                        0
sub_grade                             0
grade                                 0
installment                           0
int_rate                              0
term                                  0
funded_amnt_inv                       0
funded_amnt                           0
earliest_cr_line                      0
fico_range_low                        0
fico_range_high                       0
inq_last_6mths                        0
last_fico_range_low                   0
loan_amnt                             0
last_pymnt_amnt                       0
collection_recovery_fee               0
recoveries                            0
total_rec_late_fee                    0
total_rec_int                         0
total_rec_prncp                       0
total_pymnt_inv                       0
total_pymnt                           0
out_prncp_inv                         0
out_prncp                             0
initial_list_status                   0
total_acc                             0
revol_bal                             0
pub_rec                               0
open_acc                              0
debt_settlement_flag                  0

A continuación, vamos a observar las variables de tipo `object` y ver cuantos tipos de valores contienen.

In [7]:
lendingclub1.select_dtypes("object").nunique().sort_values()

term                         2
hardship_flag                2
application_type             2
initial_list_status          2
disbursement_method          2
pymnt_plan                   2
debt_settlement_flag         2
verification_status          3
home_ownership               5
grade                        7
loan_status                  7
emp_length                  11
purpose                     14
issue_d                     30
sub_grade                   35
last_pymnt_d                47
last_credit_pull_d          48
addr_state                  51
int_rate                   201
earliest_cr_line           712
zip_code                   933
revol_util                1271
title                     2071
emp_title               214509
url                     884876
dtype: int64

Observamos que hay muchos tipos de valores en url, lo que podría ser un impedimento a la hora de realizar nuestro modelos así como escasa aportación de información a la hora de determinar el `loan_status`.

Y vemos los NA que contienen

In [8]:
lendingclub1.select_dtypes("object").isna().sum()

term                        0
int_rate                    0
grade                       0
sub_grade                   0
emp_title               52693
emp_length              51193
home_ownership              0
verification_status         0
issue_d                     0
loan_status                 0
pymnt_plan                  0
url                         0
purpose                     0
title                     132
zip_code                    0
addr_state                  0
earliest_cr_line            0
revol_util                489
initial_list_status         0
last_pymnt_d              758
last_credit_pull_d         38
application_type            0
hardship_flag               0
disbursement_method         0
debt_settlement_flag        0
dtype: int64

In [ ]:
lendingclub1["title"].value_counts()

In [ ]:
lendingclub1_float64 = lendingclub1.select_dtypes("float64")
lendingclub1_float64

In [ ]:
lendingclub1_float64["total_bal_ex_mort"].describe()

In [ ]:
lendigclub_v2 = lendingclub1.drop(['id',
 'funded_amnt',
 'funded_amnt_inv',
 'installment',
 'emp_title',
 'emp_length',
 'issue_d',
  "zip_code",                     
 'pymnt_plan',
 'url',
 'title',
 'addr_state',
 'dti',
 'earliest_cr_line',
 'fico_range_low',
 'fico_range_high',
 'inq_last_6mths',
 'pub_rec',
 'initial_list_status',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_late_fee',                   
 'last_pymnt_d',
 'last_pymnt_amnt',
 'last_credit_pull_d',
 'last_fico_range_high',
 'last_fico_range_low',
 'policy_code',
 'application_type',
 'bc_open_to_buy',
 'mo_sin_old_il_acct',
 'mo_sin_rcnt_rev_tl_op',
 'mo_sin_rcnt_tl',
 'mths_since_recent_bc',
 'num_actv_bc_tl',
 'num_bc_sats',                   
 'num_rev_accts',
 'num_tl_120dpd_2m',
 'num_tl_90g_dpd_24m',
 'num_tl_op_past_12m',
 'pct_tl_nvr_dlq',
 'disbursement_method',
 'debt_settlement_flag',
  "mths_since_recent_inq",
"bc_util",
 "percent_bc_gt_75",
 "revol_util",
"avg_cur_bal" ], axis = 1)

In [ ]:
lendingclub1.to_csv('./data/01_intermidiate_general.csv', index = False)

In [ ]:
lendigclub_v2.info()

Las varaibles de `term` y `int_rate`Contienen variables categoricas que habría que pasar a numericas

In [ ]:
sin_months = lendigclub_v2["term"].str.strip("months")
sin_months = pd.to_numeric(sin_months)
lendigclub_v2["term"] = sin_months

In [ ]:
int_numeric = lendigclub_v2["int_rate"].str.strip("%")
int_numeric = pd.to_numeric(int_numeric)
lendigclub_v2["int_rate"] = int_numeric/100

Comprobamos que se han cambiado de tipo

In [ ]:
lendigclub_v2.info()

### Transformación de dummies

In [ ]:
X = lendigclub_v2.drop(['loan_status'], axis=1)
encoded_all = pd.get_dummies(X)
df_c = pd.concat([encoded_all, lendigclub_v2['loan_status']], axis=1)
df_c_prueba_sin_current = df_c[df_c["loan_status"]!="Current"]

### Transformación de la variable Target

Vemos que en nuestra variable target tenemos 7 valores posibles, para este trabajo haremos un encode entre las que sean Fully Paid y el resto de variables. Por lo tanto las que sean Fully Paid tendrán como valor el 1 y el resto tomarán el valor 0.

In [9]:
lendingclub1["loan_status"].value_counts()

Current               422685
Fully Paid            345520
Charged Off            97047
Late (31-120 days)     11168
In Grace Period         5507
Late (16-30 days)       2915
Default                   34
Name: loan_status, dtype: int64

In [ ]:
df_c_prueba_sin_current['loan_status'].mask(df_c_prueba_sin_current['loan_status'] == 'Fully Paid', '1', inplace=True)
df_c_prueba_sin_current['loan_status'].mask(df_c_prueba_sin_current['loan_status'] != '1', '0', inplace=True)
df_c_prueba_sin_current

### Dataset final para los modelos

In [ ]:
df_c_prueba_sin_current.to_csv('./data/03_processed.csv', index = False)